FROM amazoncorretto:17.0.7-alpine

WORKDIR /app
ARG JAR_FILE=build/libs/spring-ai-0.0.1-SNAPSHOT.jar

RUN apk add --update git
RUN git clone https://github.com/gnosia93/spring-ai.git && \
cd spring-ai && \
./gradlew build && \
cp ${JAR_FILE} /app/app.jar

ENTRYPOINT ["java","-jar","/app/app.jar"]
